version: '3.8'

services:
  server:
    build: ./server
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: ${JWT_EXPIRE}
      JWT_COOKIE_EXPIRE: ${JWT_COOKIE_EXPIRE}
      RESET_PASSWORD_EXPIRATION: ${RESET_PASSWORD_EXPIRATION}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_EMAIL: ${SMTP_EMAIL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      FROM_EMAIL: ${FROM_EMAIL}
      FROM_NAME: ${FROM_NAME}
      DATABASE_URL_DEVELOPMENT: ${DATABASE_URL_DEVELOPMENT}
      DATABASE_URL_PRODUCTION: ${DATABASE_URL_PRODUCTION}
      DATABASE_URL_TEST: ${DATABASE_URL_TEST}
      WHITELIST: ${WHITELIST}
